# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photograph', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photoseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('describtion', models.CharField(max_length=100)),
                ('images', models.ManyToManyField(to='photograph.Photo')),
            ],
        ),
    ]
