# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photo', '0008_merge_20171206_1332'),
        ('accounts', '0005_photographer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photoseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('describtion', models.CharField(max_length=100)),
                ('images', models.ManyToManyField(to='photo.Photo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Photographer', verbose_name='Fotograf')),
            ],
        ),
    ]
