# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-09 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoseries', '0002_auto_20180106_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoseries',
            name='images',
        ),
        migrations.AddField(
            model_name='photoseries',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
