# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-09 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photo_categories'),
        ('photoseries', '0003_auto_20180109_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoseries',
            name='images',
            field=models.ManyToManyField(to='photos.Photo'),
        ),
    ]
