# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoseries', '0004_photoseries_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoseries',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
