# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoseries', '0005_photoseries_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoseries',
            old_name='describtion',
            new_name='description',
        ),
    ]
