# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoseries', '0007_auto_20180118_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoseries',
            old_name='describtion',
            new_name='description',
        ),
    ]
