# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='images',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='series',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
