# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.Profile')),
            ],
            bases=('accounts.profile',),
        ),
    ]
