# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_photographer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Profile'),
        ),
    ]
