# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20180106_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='categories',
            field=models.ManyToManyField(to='photos.PhotoCategory'),
        ),
    ]
