# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photo_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='order_copy',
            field=models.BooleanField(default=False),
        ),
    ]
