# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photo_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='owner',
        ),
    ]
