# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_photo_owner'),
        ('photos', '0006_photo_order_copy'),
    ]

    operations = [
    ]
