# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photo', '0007_auto_20171205_1918'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photoseries', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ManyToManyField(to='photo.Photo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('series', models.ManyToManyField(to='photoseries.Photoseries')),
            ],
        ),
    ]
