# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20171127_2107'),
        ('photo', '0004_auto_20171128_1124'),
    ]

    operations = [
    ]
