# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20171205_1317'),
        ('photo', '0007_auto_20171205_1918'),
    ]

    operations = [
    ]
