# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Tisch', max_length=42)),
                ('tables', models.ManyToManyField(to='tables.Table')),
            ],
        ),
    ]
