# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_tag_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
