# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_tag_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='updated',
        ),
    ]
